kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.10.0.0/16"  # Pods in Cluster 2 will use 10.10.x.x
  serviceSubnet: "10.20.0.0/16"  # Services in Cluster 2 will use 10.20.x.x
nodes:
  - role: control-plane
    extraMounts:
      - containerPath: /etc/kubernetes/manifests/kube-proxy.yaml
        hostPath: ./kube-proxy-ipvs-config.yaml
    extraPortMappings:
      - containerPort: 15021
        hostPort: 15031
        protocol: TCP
      - containerPort: 15012
        hostPort: 15022
        protocol: TCP
      - containerPort: 15443
        hostPort: 15543
        protocol: TCP
      - containerPort: 15017
        hostPort: 15117
        protocol: TCP
      - containerPort: 8080
        hostPort: 9090
        protocol: TCP
      - containerPort: 8443
        hostPort: 9443
        protocol: TCP
  - role: worker