kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "192.168.0.0/16"  # Pods in Cluster 1 will use 192.168.x.x
  serviceSubnet: "192.169.0.0/16"  # Services in Cluster 1 will use 192.169.x.x
nodes:
  - role: control-plane
