kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "192.168.0.0/16"  # Pods in Cluster 1 will use 192.168.x.x
  serviceSubnet: "192.169.0.0/16"  # Services in Cluster 1 will use 192.169.x.x
nodes:
  - role: control-plane
    extraMounts:
      - containerPath: /etc/kubernetes/manifests/kube-proxy.yaml
        hostPath: ./kube-proxy-ipvs-config.yaml
    extraPortMappings:
      - containerPort: 8200
        hostPort: 8200
        protocol: TCP
      - containerPort: 8201
        hostPort: 8201
        protocol: TCP
      - containerPort: 15021
        hostPort: 15021
        protocol: TCP
      - containerPort: 15443
        hostPort: 15443
        protocol: TCP
      - containerPort: 15012
        hostPort: 15012
        protocol: TCP
      - containerPort: 15017
        hostPort: 15017
        protocol: TCP
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
      - containerPort: 8443
        hostPort: 8443
        protocol: TCP