apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster2-pool
  namespace: metallb-system
spec:
  addresses:
   - 172.18.0.170-172.18.0.180
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cluster2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - cluster2-pool
