apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster1-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.150-172.18.0.160
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cluster1-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - cluster1-pool
