apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-lb
  namespace: metallb-system
spec:
  addresses:
  - 192.169.0.240-192.169.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal-lb
  namespace: metallb-system
spec:
  ipAddressPools:
  - internal-lb
