---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
      worker_processes 1;

      events {
          worker_connections 1024;
      }

      http {
          server {
              listen 8080;

              # Proxy non-PII data requests to Cluster 2
              location /cluster2/nonpiidata {
                  proxy_pass http://gdpr-api.default.svc.cluster.local:9000/nonpiidata;
              }

              # Proxy PII data requests to Cluster 2
              location /cluster2/piidata {
                  proxy_pass http://gdpr-api.default.svc.cluster.local:9000/piidata;
              }

              # Default location
              location / {
                  return 404;
              }
          }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
