apiVersion: v1
kind: Service
metadata:
  name: ngx-svc-cluster2
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080