apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nginx-gw-1
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: nginx-tls-secret
    hosts:
    - "ngx-svc-cluster1.default.svc.cluster.local"