apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
  name: nginx-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
