apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ngx-svc-cluster1
  namespace: default
spec:
  hosts:
  - "ngx-svc-cluster1.default.svc.cluster.local"
  gateways:
  - istio-system/nginx-gw-1
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: ngx-svc-cluster1.default.svc.cluster.local
        port:
          number: 8080
